### ISSUE TITLE
Handle multi-file examples

### ISSUE THREAD

**Issue by nielsle** [zxey/cargo-examples#1]
It could be nice to be able to run multi-file examples as well,

https://doc.rust-lang.org/cargo/guide/project-layout.html

Thank you for a nice subcommand. This is really useful

**Comment by zxey** [comment]
Glad you found it useful.

I did not know about multi-file examples, it is now implemented and works as with single file examples.

I also implemented running subproject examples in examples directory, technically cargo does not recognize them as examples as they cannot be ran with `cargo run --example dir_name` but a lot of projects uses them that way.

Thank you for raising this issue.
