### ISSUE TITLE
Feature Request: run examples defined in Cargo manifest

### ISSUE THREAD

**Issue by rparrett** [zxey/cargo-examples#5]
It is possible to use `[[example]]` to configure example targets with arbitrary paths, including single rust files in subdirectories of `examples` with filenames that are not `main.rs`.

https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples

An example of these sorts of examples:

https://github.com/bevyengine/bevy/blob/latest/Cargo.toml#L146

That example is runnable with `cargo run --example move_sprite`

But `cargo-examples` doesn't currently recognize these examples.

**Comment by zxey** [comment]
Closing issue, feature is implemented in #7 and published to crates.io as version 0.4.0.
